name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  eval:
    name: Evaluate flake
    runs-on: ubuntu-latest

    outputs:
      lib-matrix: ${{ steps.generate.outputs.lib }}
      module-matrix: ${{ steps.generate.outputs.module }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Generate matrix
        id: generate
        run: |
          set -eu

          for dir in "lib" "module"; do
            pushd test/"$dir"
            echo "$dir=$(nix eval --show-trace --json .#githubWorkflow.matrix)" >> "$GITHUB_OUTPUT"
            popd
          done

  # would be nice to have another matrix for these but meh
  test-lib:
    needs: eval

    strategy:
      matrix: ${{ fromJSON(needs.eval.outputs.lib-matrix) }}

    name: Build (lib/${{ matrix.attr }})
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Qemu
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "arm64"

      - name: Install Nix
        if: matrix.arch != 'aarch64'
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Install Nix (with aarch64)
        if: matrix.arch == 'aarch64'
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: "extra-platforms = aarch64-linux arm-linux"

      - name: Build ${{ matrix.attr }}
        run: |
          cd test/lib
          nix build -L .#${{ matrix.attr }}

  test-module:
    needs: eval

    strategy:
      matrix: ${{ fromJSON(needs.eval.outputs.module-matrix) }}

    name: Build (module/${{ matrix.attr }})
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Qemu
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "arm64"

      - name: Install Nix
        if: matrix.arch != 'aarch64'
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Install Nix (with aarch64)
        if: matrix.arch == 'aarch64'
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: "extra-platforms = aarch64-linux arm-linux"

      - name: Build ${{ matrix.attr }}
        run: |
          cd test/module
          nix build -L .#${{ matrix.attr }}
