name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  eval:
    strategy:
      matrix:
        test: [lib, module]

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v26

      - name: generate matrix
        run: |
          set -euxo pipefail

          cd test/${{ matrix.test }}
          nix eval --show-trace --json .#githubWorkflow.matrix > matrix-${{ matrix.test }}.json

      - name: store matrix
        uses: actions/upload-artifact@v3
        with:
          name: matrix-${{ matrix.test }}
          path: test/${{ matrix.test }}/matrix-${{ matrix.test }}.json

  read:
    needs: eval
    runs-on: ubuntu-latest

    outputs:
      lib-matrix: ${{ steps.module.outputs.result }}
      module-matrix: ${{ steps.lib.outputs.result }}

    steps:
      - uses: actions/download-artifact@v3

      - name: recover lib matrix
        id: lib
        run:
          echo "result=$(cat matrix-lib/matrix-lib.json)" >> "$GITHUB_OUTPUT"

      - name: recover module matrix
        id: module
        run:
          echo "result=$(cat matrix-module/matrix-module.json)" >> "$GITHUB_OUTPUT"

  # would be nice to have another matrix for these but meh
  test-lib:
    needs: read

    strategy:
      matrix: ${{ fromJSON(needs.read.outputs.lib-matrix) }}

    runs-on: ${{ matrix.os }}

    name: build (${{ matrix.attr }})

    steps:
      - uses: actions/checkout@v4

      - name: setup qemu
        if: matrix.arch == 'aarch64'
        run: |
          sudo apt update -y
          sudo apt install -y qemu-user-static

      - name: install nix
        if: matrix.arch != 'aarch64'
        uses: nixbuild/nix-quick-install-action@v26

      - name: install nix (with aarch64)
        if: matrix.arch == 'aarch64'
        uses: nixbuild/nix-quick-install-action@v26
        with:
          nix_conf: "extra-platforms = aarch64-linux arm-linux"

      - name: build ${{ matrix.attr }}
        run: |
          cd test/lib
          nix build -L .#${{ matrix.attr }}

  test-module:
    needs: read

    strategy:
      matrix: ${{ fromJSON(needs.read.outputs.module-matrix) }}

    runs-on: ${{ matrix.os }}

    name: build (${{ matrix.attr }})

    steps:
      - uses: actions/checkout@v4

      - name: setup qemu
        if: matrix.arch == 'aarch64'
        run: |
          sudo apt update -y
          sudo apt install -y qemu-user-static

      - name: install nix
        if: matrix.arch != 'aarch64'
        uses: nixbuild/nix-quick-install-action@v26

      - name: install nix (with aarch64)
        if: matrix.arch == 'aarch64'
        uses: nixbuild/nix-quick-install-action@v26
        with:
          nix_conf: "extra-platforms = aarch64-linux arm-linux"

      - name: build ${{ matrix.attr }}
        run: |
          cd test/module
          nix build -L .#${{ matrix.attr }}
