name: Publish on Flakehub

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Push to Flakehub
        uses: DeterminateSystems/flakehub-push@v3
        with:
          visibility: "public"
          rolling: ${{ !startsWith(github.ref, 'refs/tags/v' )}}
